Im getting this error with gulp: highcharts-ng/higcharts-ng-d.ts(27,6) : error TS1005: ';' expected.
Using gulp which is getting the resource files everytime i run gulp server.